@startuml
left to right direction
!pragma layout smetana
skin rose

entity Libro {
    isbn
    titulo
    autor
    categoria
    calificaciones
    miembros
    enUso
}

entity Socio {
    nombre
    apellido
    correo
    numeroDeSocio
    clave
    librosEnPrestamo
}

entity Sistema {
    socios
    libros
    socio
}

entity Socios {
    listaSocios
}

entity Ajustes {
    correo
    clave
}

(Socios, Sistema) -- Socio : Genera
Socio -> "1.*" Libro : Solicita prestamo
Socio -> "1" Libro : Califica
Socio --> "1.2" Ajustes : Realiza


@enduml
